name: Secret scan

on:
  push:
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks (full repo scan)
        run: |
          set -euo pipefail
          VER="8.24.3"
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v${VER}/gitleaks_${VER}_linux_x64.tar.gz | tar -xz
          ./gitleaks detect --source=. --no-git --redact --report-format sarif --report-path results.sarif
      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-results.sarif
          path: results.sarif